name: Build and Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-cli:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: nocb-linux-x64
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   name: nocb-linux-arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross for ARM64 builds
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          curl -L https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv cross /usr/local/bin/

      - name: Install dependencies (Linux x64)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libx11-dev libxcb1-dev

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build nocb binary
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ] && [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            cross build --release --bin nocb --target ${{ matrix.target }}
          else
            cargo build --release --bin nocb --target ${{ matrix.target }}
          fi
        shell: bash

      - name: Prepare binary
        run: |
          cp target/${{ matrix.target }}/release/nocb ${{ matrix.name }}
          chmod +x ${{ matrix.name }}
          strip ${{ matrix.name }}
        shell: bash

      - name: Generate SHA512 hash
        run: |
          sha512sum ${{ matrix.name }} > ${{ matrix.name }}.sha512
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ matrix.name }}
            ${{ matrix.name }}.sha512

  sign-and-release:
    needs: build-cli
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Import GPG Key
        run: echo "${{ secrets.HQ_ROTKO_GPG }}" | gpg --batch --import

      - name: Configure GPG
        run: |
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye

      - name: Sign all binaries and hashes
        run: |
          for binary in nocb-*; do
            if [[ ! "$binary" =~ \.(sha512|sig)$ ]]; then
              gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
                --detach-sign --armor --default-key hq@rotko.net --output "${binary}.sig" "$binary"

              if [[ -f "${binary}.sha512" ]]; then
                gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
                  --detach-sign --armor --default-key hq@rotko.net --output "${binary}.sha512.sig" "${binary}.sha512"
              fi
            fi
          done
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create Release
        run: |
          # Collect all unique files to upload
          FILES=()
          for file in nocb-* *.sig; do
            if [[ -f "$file" ]]; then
              FILES+=("$file")
            fi
          done

          # Remove duplicates and create release
          printf '%s\n' "${FILES[@]}" | sort -u > files_to_upload.txt

          gh release create ${{ github.ref_name }} \
            --title "nocb ${{ github.ref_name }}" \
            --generate-notes \
            $(cat files_to_upload.txt | tr '\n' ' ')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
